"""changed column time_taken to time_in_minutes

Revision ID: 5a234c1dfab9
Revises: e11e1601c3d8
Create Date: 2023-09-08 03:30:57.048922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a234c1dfab9'
down_revision = 'e11e1601c3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('time_in_minutes', sa.Integer(), nullable=True))
    op.drop_column('recipes', 'time_taken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('time_taken', sa.INTEGER(), nullable=True))
    op.drop_column('recipes', 'time_in_minutes')
    # ### end Alembic commands ###
