"""changed keys

Revision ID: e11e1601c3d8
Revises: 1f891463d8e3
Create Date: 2023-09-07 12:55:53.095704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11e1601c3d8'
down_revision = '1f891463d8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
